# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Common.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Common.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0c\x43ommon.proto\"0\n\x08\x44uration\x12\x12\n\nbegin_date\x18\x01 \x02(\x03\x12\x10\n\x08\x65nd_date\x18\x02 \x02(\x03')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DURATION = _descriptor.Descriptor(
  name='Duration',
  full_name='Duration',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='begin_date', full_name='Duration.begin_date', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='end_date', full_name='Duration.end_date', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=64,
)

DESCRIPTOR.message_types_by_name['Duration'] = _DURATION

Duration = _reflection.GeneratedProtocolMessageType('Duration', (_message.Message,), dict(
  DESCRIPTOR = _DURATION,
  __module__ = 'Common_pb2'
  # @@protoc_insertion_point(class_scope:Duration)
  ))
_sym_db.RegisterMessage(Duration)


# @@protoc_insertion_point(module_scope)
