# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: People.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='People.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0cPeople.proto\"\xad\x03\n\x14\x43haracterInformation\x12\x13\n\x0bnativeplace\x18\x01 \x02(\t\x12\x16\n\x0e\x61ncestral_home\x18\x02 \x02(\t\x12\x0f\n\x07\x64iploma\x18\x03 \x02(\t\x12,\n\x06nation\x18\x04 \x02(\x0e\x32\x1c.CharacterInformation.Nation\x12&\n\x03sex\x18\x05 \x02(\x0e\x32\x19.CharacterInformation.Sex\x12\x11\n\tnicknames\x18\x06 \x03(\t\x12\x30\n\x08religion\x18\x07 \x03(\x0e\x32\x1e.CharacterInformation.Religion\"\x1a\n\x06Nation\x12\x07\n\x03Han\x10\x00\x12\x07\n\x03Hui\x10\x01\"6\n\x03Sex\x12\x08\n\x04Male\x10\x01\x12\n\n\x06\x46\x65Male\x10\x02\x12\x0b\n\x07Unknonw\x10\x03\x12\x0c\n\x08Undefine\x10\x04\"h\n\x08Religion\x12\x10\n\x0c\x43hristianity\x10\x00\x12\t\n\x05Islam\x10\x01\x12\x0e\n\nIrreligion\x10\x02\x12\x0c\n\x08Hinduism\x10\x03\x12\x0c\n\x08\x42uddhism\x10\x04\x12\x13\n\x0fOther_religions\x10\x05\"\xff\x01\n\x06People\x12\x11\n\tpeople_id\x18\x01 \x02(\x03\x12\x0c\n\x04name\x18\x02 \x02(\t\x12*\n\x0binformation\x18\x03 \x02(\x0b\x32\x15.CharacterInformation\x12\x11\n\tevents_id\x18\x04 \x03(\x03\x12\x1e\n\x16\x62lood_relationships_id\x18\x05 \x03(\x03\x12\x17\n\x0frelationship_id\x18\x06 \x03(\x03\x12\x17\n\x0forganzations_id\x18\x07 \x03(\x03\x12\x11\n\tjudges_id\x18\x08 \x03(\x03\x12\x15\n\rjob_titles_id\x18\t \x03(\x03\x12\x19\n\x11politic_trends_id\x18\n \x03(\x03')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_CHARACTERINFORMATION_NATION = _descriptor.EnumDescriptor(
  name='Nation',
  full_name='CharacterInformation.Nation',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Han', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Hui', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=258,
  serialized_end=284,
)
_sym_db.RegisterEnumDescriptor(_CHARACTERINFORMATION_NATION)

_CHARACTERINFORMATION_SEX = _descriptor.EnumDescriptor(
  name='Sex',
  full_name='CharacterInformation.Sex',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Male', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FeMale', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Unknonw', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Undefine', index=3, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=286,
  serialized_end=340,
)
_sym_db.RegisterEnumDescriptor(_CHARACTERINFORMATION_SEX)

_CHARACTERINFORMATION_RELIGION = _descriptor.EnumDescriptor(
  name='Religion',
  full_name='CharacterInformation.Religion',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Christianity', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Islam', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Irreligion', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Hinduism', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Buddhism', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Other_religions', index=5, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=342,
  serialized_end=446,
)
_sym_db.RegisterEnumDescriptor(_CHARACTERINFORMATION_RELIGION)


_CHARACTERINFORMATION = _descriptor.Descriptor(
  name='CharacterInformation',
  full_name='CharacterInformation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nativeplace', full_name='CharacterInformation.nativeplace', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ancestral_home', full_name='CharacterInformation.ancestral_home', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='diploma', full_name='CharacterInformation.diploma', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nation', full_name='CharacterInformation.nation', index=3,
      number=4, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sex', full_name='CharacterInformation.sex', index=4,
      number=5, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nicknames', full_name='CharacterInformation.nicknames', index=5,
      number=6, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='religion', full_name='CharacterInformation.religion', index=6,
      number=7, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CHARACTERINFORMATION_NATION,
    _CHARACTERINFORMATION_SEX,
    _CHARACTERINFORMATION_RELIGION,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=446,
)


_PEOPLE = _descriptor.Descriptor(
  name='People',
  full_name='People',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='people_id', full_name='People.people_id', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='People.name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='information', full_name='People.information', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='events_id', full_name='People.events_id', index=3,
      number=4, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='blood_relationships_id', full_name='People.blood_relationships_id', index=4,
      number=5, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='relationship_id', full_name='People.relationship_id', index=5,
      number=6, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='organzations_id', full_name='People.organzations_id', index=6,
      number=7, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='judges_id', full_name='People.judges_id', index=7,
      number=8, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='job_titles_id', full_name='People.job_titles_id', index=8,
      number=9, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='politic_trends_id', full_name='People.politic_trends_id', index=9,
      number=10, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=449,
  serialized_end=704,
)

_CHARACTERINFORMATION.fields_by_name['nation'].enum_type = _CHARACTERINFORMATION_NATION
_CHARACTERINFORMATION.fields_by_name['sex'].enum_type = _CHARACTERINFORMATION_SEX
_CHARACTERINFORMATION.fields_by_name['religion'].enum_type = _CHARACTERINFORMATION_RELIGION
_CHARACTERINFORMATION_NATION.containing_type = _CHARACTERINFORMATION
_CHARACTERINFORMATION_SEX.containing_type = _CHARACTERINFORMATION
_CHARACTERINFORMATION_RELIGION.containing_type = _CHARACTERINFORMATION
_PEOPLE.fields_by_name['information'].message_type = _CHARACTERINFORMATION
DESCRIPTOR.message_types_by_name['CharacterInformation'] = _CHARACTERINFORMATION
DESCRIPTOR.message_types_by_name['People'] = _PEOPLE

CharacterInformation = _reflection.GeneratedProtocolMessageType('CharacterInformation', (_message.Message,), dict(
  DESCRIPTOR = _CHARACTERINFORMATION,
  __module__ = 'People_pb2'
  # @@protoc_insertion_point(class_scope:CharacterInformation)
  ))
_sym_db.RegisterMessage(CharacterInformation)

People = _reflection.GeneratedProtocolMessageType('People', (_message.Message,), dict(
  DESCRIPTOR = _PEOPLE,
  __module__ = 'People_pb2'
  # @@protoc_insertion_point(class_scope:People)
  ))
_sym_db.RegisterMessage(People)


# @@protoc_insertion_point(module_scope)
