# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RelationShip.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='RelationShip.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x12RelationShip.proto\"\xd7\x03\n\x0cRelationShip\x12,\n\x04type\x18\x01 \x02(\x0e\x32\x1e.RelationShip.RelationShipType\x12\'\n\x05roles\x18\x02 \x03(\x0b\x32\x18.RelationShip.RolesEntry\x12\x10\n\x08\x65vent_id\x18\x03 \x03(\t\x12\x12\n\norigins_id\x18\x04 \x03(\t\x1a@\n\nRolesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12!\n\x05value\x18\x02 \x01(\x0e\x32\x12.RelationShip.Role:\x02\x38\x01\"z\n\x10RelationShipType\x12\x0c\n\x08OtherRel\x10\x00\x12\x12\n\x0e\x44irectRelative\x10\x01\x12\x10\n\x0c\x42ussinessRel\x10\x02\x12\x10\n\x0c\x43lassMateRel\x10\x03\x12\x0e\n\nComradeRel\x10\x04\x12\x10\n\x0c\x43olleagueRel\x10\x05\"\x8b\x01\n\x04Role\x12\t\n\x05Other\x10\x00\x12\x0b\n\x07Parents\x10\x01\x12\x0c\n\x08\x43hildren\x10\x02\x12\r\n\tOfficials\x10\x03\x12\x10\n\x0c\x42ussinessMan\x10\x04\x12\r\n\tClassMate\x10\x05\x12\x0f\n\x0b\x43omradeship\x10\x06\x12\r\n\tColleague\x10\x07\x12\r\n\tSecretary\x10\x08')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_RELATIONSHIP_RELATIONSHIPTYPE = _descriptor.EnumDescriptor(
  name='RelationShipType',
  full_name='RelationShip.RelationShipType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OtherRel', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DirectRelative', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BussinessRel', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ClassMateRel', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ComradeRel', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ColleagueRel', index=5, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=230,
  serialized_end=352,
)
_sym_db.RegisterEnumDescriptor(_RELATIONSHIP_RELATIONSHIPTYPE)

_RELATIONSHIP_ROLE = _descriptor.EnumDescriptor(
  name='Role',
  full_name='RelationShip.Role',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Other', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Parents', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Children', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Officials', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BussinessMan', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ClassMate', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Comradeship', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Colleague', index=7, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Secretary', index=8, number=8,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=355,
  serialized_end=494,
)
_sym_db.RegisterEnumDescriptor(_RELATIONSHIP_ROLE)


_RELATIONSHIP_ROLESENTRY = _descriptor.Descriptor(
  name='RolesEntry',
  full_name='RelationShip.RolesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='RelationShip.RolesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='RelationShip.RolesEntry.value', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=164,
  serialized_end=228,
)

_RELATIONSHIP = _descriptor.Descriptor(
  name='RelationShip',
  full_name='RelationShip',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='RelationShip.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='roles', full_name='RelationShip.roles', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='event_id', full_name='RelationShip.event_id', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='origins_id', full_name='RelationShip.origins_id', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_RELATIONSHIP_ROLESENTRY, ],
  enum_types=[
    _RELATIONSHIP_RELATIONSHIPTYPE,
    _RELATIONSHIP_ROLE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=494,
)

_RELATIONSHIP_ROLESENTRY.fields_by_name['value'].enum_type = _RELATIONSHIP_ROLE
_RELATIONSHIP_ROLESENTRY.containing_type = _RELATIONSHIP
_RELATIONSHIP.fields_by_name['type'].enum_type = _RELATIONSHIP_RELATIONSHIPTYPE
_RELATIONSHIP.fields_by_name['roles'].message_type = _RELATIONSHIP_ROLESENTRY
_RELATIONSHIP_RELATIONSHIPTYPE.containing_type = _RELATIONSHIP
_RELATIONSHIP_ROLE.containing_type = _RELATIONSHIP
DESCRIPTOR.message_types_by_name['RelationShip'] = _RELATIONSHIP

RelationShip = _reflection.GeneratedProtocolMessageType('RelationShip', (_message.Message,), dict(

  RolesEntry = _reflection.GeneratedProtocolMessageType('RolesEntry', (_message.Message,), dict(
    DESCRIPTOR = _RELATIONSHIP_ROLESENTRY,
    __module__ = 'RelationShip_pb2'
    # @@protoc_insertion_point(class_scope:RelationShip.RolesEntry)
    ))
  ,
  DESCRIPTOR = _RELATIONSHIP,
  __module__ = 'RelationShip_pb2'
  # @@protoc_insertion_point(class_scope:RelationShip)
  ))
_sym_db.RegisterMessage(RelationShip)
_sym_db.RegisterMessage(RelationShip.RolesEntry)


_RELATIONSHIP_ROLESENTRY.has_options = True
_RELATIONSHIP_ROLESENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
# @@protoc_insertion_point(module_scope)
