# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: IdGenerate.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='IdGenerate.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x10IdGenerate.proto\"j\n\x11GenerateIdRequest\x12\x1a\n\x12generateObjectType\x18\x01 \x02(\t\x12\x1a\n\x12generateObjectByte\x18\x02 \x02(\t\x12\x0e\n\x06source\x18\x03 \x01(\t\x12\r\n\x05links\x18\x04 \x03(\t\"A\n\x12GenerateIdResponse\x12\x0f\n\x07success\x18\x01 \x02(\x08\x12\n\n\x02id\x18\x02 \x02(\x03\x12\x0e\n\x06\x65xists\x18\x03 \x01(\x08\x32\x44\n\x0bId_Generate\x12\x35\n\nGenerateId\x12\x12.GenerateIdRequest\x1a\x13.GenerateIdResponse')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_GENERATEIDREQUEST = _descriptor.Descriptor(
  name='GenerateIdRequest',
  full_name='GenerateIdRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='generateObjectType', full_name='GenerateIdRequest.generateObjectType', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='generateObjectByte', full_name='GenerateIdRequest.generateObjectByte', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='source', full_name='GenerateIdRequest.source', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='links', full_name='GenerateIdRequest.links', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=126,
)


_GENERATEIDRESPONSE = _descriptor.Descriptor(
  name='GenerateIdResponse',
  full_name='GenerateIdResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='GenerateIdResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='GenerateIdResponse.id', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='exists', full_name='GenerateIdResponse.exists', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=128,
  serialized_end=193,
)

DESCRIPTOR.message_types_by_name['GenerateIdRequest'] = _GENERATEIDREQUEST
DESCRIPTOR.message_types_by_name['GenerateIdResponse'] = _GENERATEIDRESPONSE

GenerateIdRequest = _reflection.GeneratedProtocolMessageType('GenerateIdRequest', (_message.Message,), dict(
  DESCRIPTOR = _GENERATEIDREQUEST,
  __module__ = 'IdGenerate_pb2'
  # @@protoc_insertion_point(class_scope:GenerateIdRequest)
  ))
_sym_db.RegisterMessage(GenerateIdRequest)

GenerateIdResponse = _reflection.GeneratedProtocolMessageType('GenerateIdResponse', (_message.Message,), dict(
  DESCRIPTOR = _GENERATEIDRESPONSE,
  __module__ = 'IdGenerate_pb2'
  # @@protoc_insertion_point(class_scope:GenerateIdResponse)
  ))
_sym_db.RegisterMessage(GenerateIdResponse)


import grpc
from grpc.beta import implementations as beta_implementations
from grpc.beta import interfaces as beta_interfaces
from grpc.framework.common import cardinality
from grpc.framework.interfaces.face import utilities as face_utilities


class Id_GenerateStub(object):

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GenerateId = channel.unary_unary(
        '/Id_Generate/GenerateId',
        request_serializer=GenerateIdRequest.SerializeToString,
        response_deserializer=GenerateIdResponse.FromString,
        )


class Id_GenerateServicer(object):

  def GenerateId(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_Id_GenerateServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GenerateId': grpc.unary_unary_rpc_method_handler(
          servicer.GenerateId,
          request_deserializer=GenerateIdRequest.FromString,
          response_serializer=GenerateIdResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Id_Generate', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class BetaId_GenerateServicer(object):
  """The Beta API is deprecated for 0.15.0 and later.

  It is recommended to use the GA API (classes and functions in this
  file not marked beta) for all further purposes. This class was generated
  only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
  def GenerateId(self, request, context):
    context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


class BetaId_GenerateStub(object):
  """The Beta API is deprecated for 0.15.0 and later.

  It is recommended to use the GA API (classes and functions in this
  file not marked beta) for all further purposes. This class was generated
  only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
  def GenerateId(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
    raise NotImplementedError()
  GenerateId.future = None


def beta_create_Id_Generate_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
  """The Beta API is deprecated for 0.15.0 and later.

  It is recommended to use the GA API (classes and functions in this
  file not marked beta) for all further purposes. This function was
  generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
  request_deserializers = {
    ('Id_Generate', 'GenerateId'): GenerateIdRequest.FromString,
  }
  response_serializers = {
    ('Id_Generate', 'GenerateId'): GenerateIdResponse.SerializeToString,
  }
  method_implementations = {
    ('Id_Generate', 'GenerateId'): face_utilities.unary_unary_inline(servicer.GenerateId),
  }
  server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
  return beta_implementations.server(method_implementations, options=server_options)


def beta_create_Id_Generate_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
  """The Beta API is deprecated for 0.15.0 and later.

  It is recommended to use the GA API (classes and functions in this
  file not marked beta) for all further purposes. This function was
  generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
  request_serializers = {
    ('Id_Generate', 'GenerateId'): GenerateIdRequest.SerializeToString,
  }
  response_deserializers = {
    ('Id_Generate', 'GenerateId'): GenerateIdResponse.FromString,
  }
  cardinalities = {
    'GenerateId': cardinality.Cardinality.UNARY_UNARY,
  }
  stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
  return beta_implementations.dynamic_stub(channel, 'Id_Generate', cardinalities, options=stub_options)
# @@protoc_insertion_point(module_scope)
